- name: Download mongodb release
  get_url:
    url: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.22.tgz
    dest: /tmp/mongodb.tgz
    mode: 0755
    force: 'yes'

- name: Ensure /opt/mongodb exists
  file:
    dest: /opt/mongodb
    mode: 0755
    state: directory
    owner: root
    group: root

- name: Unarchive mongodb
  unarchive:
    src: /tmp/mongodb.tgz
    dest: /opt/mongodb
    remote_src: yes

- name: Find mongodb binaries
  find:
    paths: /opt/mongodb/mongodb-linux-x86_64-3.2.22/bin/
    patterns: "*"
  register: mongodb_binaries
  changed_when: False

- name: Copy mongodb binaries
  copy:
    src: "{{ item.path }}"
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  with_items: "{{ mongodb_binaries.files }}"

- name: Ensure /var/lib/mongodb exists
  file:
    dest: /var/lib/mongodb
    mode: 0755
    state: directory
    owner: root
    group: root

- name: Ensure /var/log/mongodb exists
  file:
    dest: /var/log/mongodb 
    mode: 0755
    state: directory
    owner: root
    group: root

- name: Ensure /run/mongodb exists
  file:
    dest: /run/mongodb
    mode: 0755
    state: directory
    owner: root
    group: root

- name: Write mongodb config file
  template:
    src: mongodb.conf.j2
    dest: /etc/mongodb.conf
    owner: root
    group: root
    mode: 0755

- name: install mongodb systemd unit file
  template: src=mongodb.service.j2 dest=/etc/systemd/system/mongodb.service

- name: start mongodb
  systemd: state=started name=mongodb daemon_reload=yes